project:
  type: manuscript
  output-dir: "."

manuscript:
  article: index.qmd
  notebooks: 
    - notebook: notebooks/plots/plots.qmd  # plots

execute:
  echo: false
  warning: false
  message: false
  eval: true

format:
  html:
    css: styles.css
    fig-path: _output/notebooks/plots
    comments:
      hypothesis: true
  docx: default
  pdf: default
  jats: default

editor: visual