project:
  type: manuscript
  output-dir: _output

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/plots/plots.qmd  # plots
#    - notebook: notebooks/preprocessing/charite/charite_loading_and_preprocessing.qmd # charite preprocessing
#    - notebook: notebooks/preprocessing/dcc/dcc_loading_and_preprocessing.qmd.qmd # dcc preprocessing

format:
  html:
    comments:
      hypothesis: true
  docx: default
  pdf: default
  jats: default

execute:
  freeze: false
  cache: false
  always: true

editor: visual

