---
title: Investigating the Reuse of Biomedical Data Using the Data Citation Corpus
authors:
  - name: "name"
    affiliation: "aff"
    roles: "writing"
    corresponding: true
    orcid: "000"
---

Your text goes here.

# Methods

Identifiers and accession codes of open an restricted datasets that were found in articles by Charité's authors between the years 2020 and 2023 (henceforth referred to as the datasets) were collected as part of a separate data sharing monitoring process. Articles were defined as written by Charité's authors if at least one author had an affiliation to Charité.

Prior to looking for mentions of Charités datasets in the DCC, the datasets were standardized into a format that would maximize their chance to be found in the DCC. This was done by an automatic standardization function that extracted the accession number from each given URL of a dataset, and standardized any DOI to a uniform format. The output of that function was verified manualy in order to ensure that all datasets are indeed in the correct format (i.e. either a DOI or an accession code), with the version information removed from it.

Prior to applying several preprocessing and cleaning steps to the DCC as well, we first explored the corpus in order to make sure that there are no NAs in relevant fields. We then made sure that dates entries of pucblication years were correct. Lastly, we observed the frequency of repositories in which datasets were deposited according to the corpus, together with publication years of the mentioning articles. Once we made sure that the fundamental structure of the corpus is preoperly defined, we went on with the preprocessing steps described below.

DOIs of datasets deposited in general repositories (i.e., Zenodo, Figshare, Dryad, and OSF) were found to appear in multiple formats within the DCC. To ensure consistency, all DOIs were standardized to a uniform format. As with the Charité datasets, version information was removed from all entries. Subsequently, excess characters were stripped from both the dataset and the articles' DOIs. This included leading and trailing slashes, dots and spaces, together with any other space found within the string value of the dataset or the article's DOI. Additionally, commas were replaced with dots. DOIs of articles were likewise standardized to a uniform DOI format.

The DCC had also cases where the same DOI was listed both in the "mentioning article" field and the "mentioned dataset" field. There were cases where this was discovered only after standardizing both fields. All such cases were removed from the DCC. We have also decided to not include preprints in the analysis, and therefore all cases where the repository was listed as a preprint service were removed as well.

Following all the steps above, we looked for Charité's datasets mentions in the DCC. This step resulted in a list with cases from the DCC which had a matching dataset identifier to the ones in the Charité datasets list. From this results list, cases where the mentioning article and the article with the mentioned dataset had at least one author in common were excluded. For this step, meta data regarding the authors of each article was extracted using Openalex. Publication years of Charité's papers and of their datasets were incorporated into the results list as meta data as well.

Lastly, a sample of the remaining cases was taken in order to manualy verify the results, focusing on the following cases:

1\. Mentioning article is listed as published before 2016

2\. Mentioning article is listed as published before the publication of the dataset

3\. Publication year of mentioning article is listed as earlier than publication year of the Charité article.

{{< embed notebooks/plots/plots.qmd#fig-distinct-numbers >}}

{{< embed notebooks/plots/plots.qmd#fig-datasets-freq-dist >}}

{{< embed notebooks/plots/plots.qmd#fig-repo-dist >}}

{{< embed notebooks/plots/plots.qmd#fig-ref-by-year >}}

{{< embed notebooks/plots/plots.qmd#fig-datasets-properties >}}

{{< embed notebooks/plots/plots.qmd#fig-datasets-and-papers-years >}}
