---
title: "plots"
date: "today"
author: "Avihay Cohen"
format:
  html:
    self-contained: true
editor: visual
---

```{r setup, echo=FALSE}

if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
library(pacman)
pacman::p_load(tidyverse, DT, patchwork, RColorBrewer, here, tcltk, networkD3, htmlwidgets)

# Load _4 for counting with author overlap:

load(here("data", "wrangling_steps", "dcc_charite", "dcc_charite_joined_4_au_info.RData"))

# Load the most recent .RData file from the data\processed directory and assign it to "dcc_charite_joined_final"

# Assign the loaded object to a new variable name

load(here("data", "wrangling_steps", "dcc_charite", "dcc_charite_joined_6_covid_and_years.RData"))

dcc_charite_joined_final <- dcc_charite_joined_6_covid_and_years
rm(dcc_charite_joined_6_covid_and_years)

```

<br>

# Distinct Number of Papers and Datasets Found in the DCC - prep

<br>

```{r fig-distinct-numbers-prep}
# 1. Number of papers (dcc and charite) and of identifiers in final table (excluding author overlap cases)

counts_final <- tibble(
  `Mentioning Articles` = dcc_charite_joined_final |> select(doi_dcc) |> distinct() |> nrow(),
  `Charité Articles` = dcc_charite_joined_final |> select(doi_charite) |> distinct() |> nrow(),
  `Mentioned Datasets` = dcc_charite_joined_final |> select(data_id_merged) |> distinct() |> nrow()
)

# 2. Number of papers (dcc and charite) and of identifiers in final table (including author overlap cases)

# I'll use dcc_charite_joined_4_au_info to count, since it is one step before excluding author overlap cases.

# However, I need to *exclude* cases where the author overlap is a result of the same paper that is present once as a preprint (as "doi_charite") and once as a publication (as "doi_dcc").

# So I'll first create a table with the cases suspected of being preprint-publication cases and check them for author overlap:

dcc_charite_blank_journals <- dcc_charite_joined_4_au_info |> # get all cases from the step before "author overlap exclusion" step
  dplyr::filter(journal == "") |> # get only cases where there's no journal information, because most of them are preprint cases
  rowwise()  |> 
  mutate(
    common_au = {
      common <- intersect(
        str_split(authors_dcc, ";")[[1]], 
        str_split(authors_charite, ";")[[1]]
      )
      if (length(common) > 0) paste(common, collapse = ";") else NA
    }
  ) |>
  ungroup() # check for author overlap in these cases only

# Then I'll verify that I should keep cases with partial overlap, since they are presumably cases of author overlap which are not a result of preprint-publication relation:

  # # Get partial overlap cases
  #
  # dcc_charite_blank_journals |>
  #   dplyr::filter(!is.na(common_au)) |> # remove cases where there's no overlap at all (they are irrelevant for this table in any case)
  #   dplyr::filter(authors_dcc != common_au) |> # remove cases where there's a full overlap
  #   ungroup() |>
  #   View()
  #
  # # I've checked each one manually and they are indeed not preprints - so they will be included in the "matched-with-author-overlap".

# Now I'll manually check the full (exact) overlap cases - these are suspected to be preprints:

dcc_charite_blank_journals_exact_overlap <- dcc_charite_blank_journals |>
  dplyr::filter(authors_dcc == common_au) |> # get cases with full overlap out of journal == ""
  select(doi_charite, doi_dcc) |>
  distinct()

# Results (distinct): 4 preprints, 2 datasets in doi_dcc(!). So those should be removed from "with-author-overlap".
# Note: they are already removed from the final matched list, because of the exact author overlap.

# Now I'll look for author overlap cases in general:

dcc_charite_all_exact_overlap <- dcc_charite_joined_4_au_info |> # get all cases from the step before "author overlap exclusion" step
  dplyr::filter(authors_dcc == authors_charite) |> 
  select(doi_charite, doi_dcc) |> 
  distinct()

# I've checked them manually as well, and they are also preprints-publications (10.1016/j.dib.2021.107320 is actually a data article under doi_dcc). So they should also be removed.

# Now I'll bind _all_exact_overlap cases with _blank_journals_exact_overlap cases, to create a table with preprint-publication cases to remove from matched-list-including-overlap

cases_to_remove <- dcc_charite_blank_journals_exact_overlap |> 
    bind_rows(dcc_charite_all_exact_overlap) |> 
  distinct()

# Remove those preprint-publication cases

dcc_charite_joined_w_au_ov <- dcc_charite_joined_4_au_info |> 
  anti_join(cases_to_remove, by = c("doi_charite", "doi_dcc")) 

# Get counts

counts_w_au_ov <- tibble(
  `Mentioning Articles` = dcc_charite_joined_w_au_ov |> select(doi_dcc) |> distinct() |> nrow(),
  `Charité Articles` = dcc_charite_joined_w_au_ov |> select(doi_charite) |> distinct() |> nrow(),
  `Mentioned Datasets` = dcc_charite_joined_w_au_ov |> select(data_id_merged) |> distinct() |> nrow()
)

# Prepare count tibbles (with and without author overlap cases) for plotting

combined_count_tibbles <- counts_final |>
  bind_rows(counts_w_au_ov,
            .id = "tibble_source") |>
  select(-`Charité Articles`) |> 
  mutate(tibble_source = recode(tibble_source,
                                "1" = "No Author Overlap",
                                "2" = "Inc. Author Overlap")) |> 
  pivot_longer(cols = -tibble_source, names_to = "variable", values_to = "value") |> 
  mutate(variable = fct_reorder(variable, value, .desc = TRUE))

# save as RData
save_cr(combined_count_tibbles, file = file.path(here("data",
                                                      "tables_for_plots",
                                                      "combined_count_tibbles.RData")))


```

# Distribution Frequency of Datasets References

```{r fig-datasets-freq-dist-prep}

ds_freq <- dcc_charite_joined_final |>
  group_by(data_id_merged) |>
  summarise(n = n())

# save as RData
save_cr(ds_freq, file = file.path(here("data",
                                       "tables_for_plots",
                                       "ds_freq.RData")))
```

# Distribution of References Across Repositories

```{r fig-repo-dist-prep}

rep_dt <- dcc_charite_joined_final |> 
  group_by(repository) |> 
  summarise(n = n()) |> 
  arrange(desc(n)) |> 
  mutate(repository = case_when(
    repository == "NCBI dbGaP (DataBase of Genotypes And Phenotypesgenotypes and phenotypes)" ~ "NCBI dbGaP",
    repository == "figshare" ~ "Figshare",
    repository == "The European Genome-phenome Archive(EGA)" ~ "EGA",
    repository == "Gene Expression Omnibus (GEO)" ~ "GEO",
    repository == "PRIDE Proteomics Identification Database" ~ "PRIDE",
    repository == "NCBI Reference Sequence Database" ~ "NCBI RefSeq",
    repository == "European Nucleotide Archive" ~ "ENA",
    repository == "The Protein Data Bank" ~ "PDB",
    .default = repository # shorten rep names for a nicer appearance
  ))

# save as RData
save_cr(rep_dt, file = file.path(here("data",
                                       "tables_for_plots",
                                       "rep_dt.RData")))

```

# Datasets References by Year

```{r fig-ref-by-year-prep}

year_dcc_dt_all <- dcc_charite_joined_final |>
  select(doi_dcc, data_id_merged, publication_year_dcc) |> 
  distinct() |> 
  count(data_id_merged, sort = TRUE)

year_dcc_dt_all_for_plot <- year_dcc_dt_all |>
  inner_join(dcc_charite_joined_final, by = "data_id_merged")

year_dcc_dt_all_for_plot_agg <- year_dcc_dt_all_for_plot |> 
  mutate(data_id_merged = case_when(
    !data_id_merged %in% c("6y2e", "gse14764", "gse148729", "gse55235") ~ "Others",
    .default = data_id_merged)) |> 
  group_by(data_id_merged, publication_year_dcc) |> 
  summarise(count = n(), .groups = "drop") |> 
  dplyr::filter(publication_year_dcc != "2023")

# save as RData
save_cr(year_dcc_dt_all_for_plot_agg, file = file.path(here("data",
                                                            "tables_for_plots",
                                                            "year_dcc_dt_all_for_plot_agg.RData")))

```

# Datasets Access, Repositories and Covid-relationship

```{r fig-datasets-properties-prep}

# Prepare table for sankey:

dcc_charite_for_sankey <- dcc_charite_joined_final |>
  select(data_id_merged, data_access, covid_related, repository) |>
  distinct() |>
  mutate(acc_nr_or_doi = case_when(str_starts(data_id_merged, "10.") ~ "DOI", .default = "Accession Number"))

# Create links

links_ac_access <- dcc_charite_for_sankey |>
  mutate(source = case_when(acc_nr_or_doi == "Accession Number" ~ "Accession Number",
                            .default = "DOI"),
         target = case_when(data_access == "yes" ~ "Full Access",
                            data_access == "restricted" ~ "Restricted Access",
                            .default = "access not checked yet")) |>
  count(source, target) |>
  rename(value = n) |>
  as.data.frame()

links_access_rep <- dcc_charite_for_sankey |>
  mutate(source = case_when(data_access == "yes" ~ "Full Access",
                            data_access == "restricted" ~ "Restricted Access",
                            .default = "access not checked yet"),
         target = case_when(
           repository == "ncbi dbgap (database of genotypes and phenotypesgenotypes and phenotypes)" ~ "NCBI dbGaP",
           repository == "figshare" ~ "figshare",
           repository == "the european genome-phenome archive(ega)" ~ "EGA",
           repository == "gene expression omnibus (geo)" ~ "GEO",
           repository == "pride proteomics identification database" ~ "PRIDE",
           repository == "ncbi reference sequence database" ~ "NCBI RefSeq",
           repository == "european nucleotide archive" ~ "ENA",
           repository == "the protein data bank" ~ "PDB",
           .default = repository)) |>
  count(source, target) |>
  rename(value = n) |>
  as.data.frame()

links_rep_covid <- dcc_charite_for_sankey |>
  mutate(source = case_when(
           repository == "ncbi dbgap (database of genotypes and phenotypesgenotypes and phenotypes)" ~ "NCBI dbGaP",
           repository == "figshare" ~ "figshare",
           repository == "the european genome-phenome archive(ega)" ~ "EGA",
           repository == "gene expression omnibus (geo)" ~ "GEO",
           repository == "pride proteomics identification database" ~ "PRIDE",
           repository == "ncbi reference sequence database" ~ "NCBI RefSeq",
           repository == "european nucleotide archive" ~ "ENA",
           repository == "the protein data bank" ~ "PDB",
           .default = repository),
         target = case_when(covid_related == 1 ~ "Covid Related",
                            covid_related == 0 ~ "Not Covid Related",
                            .default = "covid not checked yet")) |>
  count(source, target) |>
  rename(value = n) |>
  as.data.frame()

links_all <- bind_rows(links_ac_access, links_access_rep, links_rep_covid)

# save as RData
save_cr(links_all, file = file.path(here("data",
                                         "tables_for_plots",
                                         "links_all.RData")))

```

# Datasets and Citing Papers Publication Years

```{r Datasets and Citing Papers Publication Years, echo=FALSE}

dif_for_plot <- dcc_charite_joined_final |>
  select(publication_year_dcc, charite_id_year) |>
  distinct() |>
  mutate(dif = publication_year_dcc - charite_id_year) |>
  dplyr::filter(dif >= 0 & !is.na(dif)) |> 
  dplyr::filter(dif < 24)

# save as RData
save_cr(dif_for_plot, file = file.path(here("data",
                                            "tables_for_plots",
                                            "dif_for_plot.RData")))
```
