---
title: "ds_added_and_datastet_load_prep_match_clean"
date: "today"
author: "Avihay Cohen"
format:
  html:
    self-contained: true
editor: visual
---

```{r setup, echo=FALSE}

Sys.setenv(LANG = "EN")  # Set environment language to English

if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
library(pacman)
pacman::p_load(tidyverse, DT, patchwork, RColorBrewer, here, tcltk, networkD3, readxl, lubridate, stringi)

save_cr <- function(..., file) {
  dir_path <- dirname(file)
  if (!dir.exists(dir_path)) {
    dir.create(dir_path, recursive = TRUE)
  }
  save(..., file = file)
} # wrapper for save() with automatic directory creation

write_csv_cr <- function(x, file, ...) {
  dir_path <- dirname(file)
  if (!dir.exists(dir_path)) {
    dir.create(dir_path, recursive = TRUE)
  }
  write.csv(x, file = file, ...)
} # wrapper for write.csv() with automatic directory creation

# fucntion to load latest metadata version

load_latest_metadata_update <- function() {
  # Define target directory using here()
  rda_dir <- here("data", "verification", "metadata all", "datasets_metadata_master_updated", "rda")
  
  # List all .RData files
  files <- list.files(rda_dir, pattern = "\\.RData$", full.names = TRUE)
  
  # Extract numeric suffixes from filenames
  suffixes <- sub(".*_([0-9]+)\\.RData$", "\\1", files)
  suffixes_num <- as.integer(suffixes)
  
  # Find file with highest suffix
  max_index <- which.max(suffixes_num)
  latest_file <- files[max_index]
  
  # Load the file
  loaded_vars <- load(latest_file, envir = .GlobalEnv)
  
  # Extract and print the base file name without extension
  file_base <- tools::file_path_sans_ext(basename(latest_file))
  current_suffix <- sub(".*_(\\d+)$", "\\1", file_base)
  next_suffix <- sprintf("%03d", as.integer(current_suffix) + 1)
  next_file_base <- sub("_(\\d+)$", paste0("_", next_suffix), file_base)
  message("✅ Loaded: ", file_base, "\nNext file version: ", next_file_base)
  
  # Return the object invisibly
  invisible(get(loaded_vars[1], envir = .GlobalEnv))
}

```

# 1. Loading 2 joined lists of 4 sources (numbat, data articles, datastet, added ids)

```{r Loading 2 joined lists of 4 sources}

# load joined dcc numbat and data articles
load(here("data",
          "wrangling_steps",
          "dcc_charite",
          "dcc_charite_joined_4_rm_au_ov.RData"))

dcc_charite_joined_final <- dcc_charite_joined_4_rm_au_ov

# load joined dcc datastet and added
load(here("data",
          "wrangling_steps",
          "dcc_datastet_and_added",
          "dcc_ds_and_added_joined_4_rm_au_ov.RData")) # CHANGE TO THE MOST RECENT!

dcc_ds_joined_final <- dcc_ds_and_added_joined_4_rm_au_ov

```

# 2. Bind

```{r Bind}

# 1. Prepare for binding

# Get column names that exist only in each joined list

only_in_dcc_ds <- setdiff(colnames(dcc_ds_joined_final),
                          colnames(dcc_charite_joined_final))

only_in_dcc_charite <- setdiff(colnames(dcc_charite_joined_final),
                               colnames(dcc_ds_joined_final))

# View different column names between the lists
tibble(
  # left column: values only in dcc_ds, padded with NA if dcc_charite has more entries
  dcc_ds_joined_final = c(only_in_dcc_ds, rep(NA, max(0, length(only_in_dcc_charite) - length(only_in_dcc_ds)))),
  # right column: opposite
  dcc_charite_joined_final     = c(only_in_dcc_charite, rep(NA, max(0, length(only_in_dcc_ds) - length(only_in_dcc_charite))))
) |> View()

# Rename columns in dcc_ds to match dcc_charite columns (just because their were named first)

dcc_ds_for_binding <- dcc_ds_joined_final |> 
  rename(
    
    # renaming columns to the dcc_charite column names (which will merge them when binding)
    doi_charite = doi_datastet_and_added, # the col "doi_no_ver_info" will be relevant only for numbat
    data_identifier_orig_1st_entry = context, # for ds it's "context". For numbat it's original typed-in id
    slug_charite = slug_datastet_and_added,
    data_id_m_val = m_val,
    data_id_source = source_datastet_and_added,
    publication_year_charite = publication_year_datastet_and_added,
    authors_charite = authors_datastet_and_added,

    
    # renaming columns in order to keep their source apparent
    doi_year_from_datastet = year, # to mark that this column originated from Datastet source file
    category = Category, # just lower-casing
    originally_detected_id_for_added = detected_id # relevant only in case an additional id was matched
    ) |> 
  select(-validate) # in the matched list (and only there), all values are TRUE anyway 

# So the columns that are relevant only for numbat + data articles, and kept with their names:
# data_id_secondary, data_access, in_dashboard, doi_no_ver_info 

# And columns that are relevant only for datastet + added, and kept with their names:
# added_id
  
dcc_charite_for_binding <- dcc_charite_joined_final |> 
    rename(
      data_id_source = source_charite, # renaming was done in ds_added as well
      category = Category, # just lower-casing
      extracted_id = data_id,  # in ds it's extracted from "contex". in numnbat - first processing of typed-in
      detected_in_dcc = detected_id) |> # relevant only in case an where there were primary and secondary ids

   mutate(in_numbat_or_data_articles = TRUE) |> # adding "TRUE" to this column which originated from datastet_and_added
   select(-c(validated, # all values are TRUE anyway
          listed_in_numbat_output, # relevant only for data articles values and values here are all FALSE
          data_identifier_orig_2nd_entrie)) # in the matched list (and only there), this column is the same as 1st_entry
          
# 2. Bind

dcc_detected_ids_all_sources <- bind_rows(
  dcc_charite_for_binding,
  dcc_ds_for_binding
)

# save
save_cr(dcc_detected_ids_all_sources, file = file.path(here("data", "wrangling_steps", "all_sources_binded",
                                                        "dcc_detected_ids_all_sources_1_binded.RData")))
```

# 3. Add Metadata

```{r Add metadata}

### FOR NOW, I'LL WORK ONLY ON NUMBAT + DA. ONCE I GET THE DS+ADDED OD LIST, I'LL FILTER IN THE DS QMD AND RUN THIS QMD AGAIN.

dcc_detected_ids_numbat <- dcc_detected_ids_all_sources |> 
  dplyr::filter(data_id_source %in% c("numbat", "data_articles"))

# Add metadata: 
# data access, license, human/not, covid/not, doi/acc_n, repository, is in DAS

# load metadata file
load_latest_metadata_update()

# prepare for joining

metadata_for_joining <- datasets_metadata_master_updated_012 |>
  select(doi_charite,
         dataset_for_matching,
         data_id_source,
         listed_in_numbat_output,
         data_access,
         license,
         human_data,
         covid_related,
         orig_id_is_doi,
         repository,
         data_availability_statement,
         charite_id_year
         )

# add to _joined
dcc_detected_ids_numbat_w_metadata <- dcc_detected_ids_numbat |>
  select(-data_id_source) |> # metadata master file has the most updated values
  left_join(metadata_for_joining,
            by = c("doi_charite", "dataset_for_matching")) |> 
  mutate(
    repository = coalesce(repository.y, repository.x),
    data_access = coalesce(data_access.y, data_access.x) # get new value unless the new value is NA, then fall back to old value
  ) |>
  select(
    -repository.y, -repository.x,
    -data_access.y, -data_access.x)

# check
dcc_detected_ids_numbat_w_metadata |> 
  dplyr::filter(
    is.na(data_access)
    | is.na(license)
    | is.na(human_data)
    | is.na(covid_related)
    | is.na(orig_id_is_doi)
    | is.na(repository)
  ) |>  View()

# Add coluns for analysis

dcc_detected_ids_numbat_w_metadata <- dcc_detected_ids_numbat_w_metadata |> 
  mutate(
    das_for_analysis = case_when(
      is.na(data_availability_statement) ~ NA_character_,
      data_availability_statement %in% c("TRUE", "yes") ~ "TRUE",
      .default = "FALSE"
    ),
    license_for_analysis = case_when(
      is.na(license) ~ NA_character_,
      license %in% c("CC0", "cc0", "CC BY", "cc-by", "CC BY-NC", "CC BY;CC0", "CC BY-NC-SA", "CC BY-NC-ND", "GNU GPLv3", "MIT", "GNU") ~ "TRUE",
      .default = "FALSE"
    )
  )

# save
save_cr(dcc_detected_ids_numbat_w_metadata, file = file.path(here("data", "wrangling_steps", "all_sources_binded",
                                                        "dcc_detected_ids_numbat_w_metadata_2_metadata.RData")))
# NOTE! THIS IS ONLY NUMBAT FOR NOW!

```

# 4. Verify Results

```{r Verify results}


# 1. Check for contradictory datastet metadata for the same charite id

dcc_detected_ids_all_sources |> 
  select(doi_charite, doi_year_from_datastet) |>
  distinct() |> 
  group_by(doi_charite) |> 
  summarise(n = n()) |> 
  dplyr::filter(n>1) |> 
  View()


```

# 5. Create Results Tables

```{r Create results tables}


```
